Add color support, and better non-interactive mode handling

diff --git a/dot_local/share/bash/functions b/dot_local/share/bash/functions
--- a/dot_local/share/bash/functions
+++ b/dot_local/share/bash/functions
@@ -32,13 +32,33 @@ function execute_remote_command {
   # shellcheck disable=SC1090
   [ -f "${keychain_init}" ] && source "${keychain_init}"
 
+  # Detect color support
+  local use_color=0
+  if [[ -z "${NO_COLOR:-}" ]] && [[ "${TERM:-}" != "dumb" ]] && { [[ -t 1 ]] || [[ -t 2 ]]; }; then
+    use_color=1
+  fi
+
+  # Set color codes based on terminal support
+  local dim_white="" green="" dim_red="" reset=""
+  if [[ $use_color -eq 1 ]]; then
+    dim_white="\033[2;37m"
+    green="\033[32m"
+    dim_red="\033[2;31m"
+    reset="\033[0m"
+  fi
+
   echo "Executing: cmd on ${remote_hosts[*]}"
   for rhost in "${remote_hosts[@]}"; do
     {
-      { ssh -A -q -t "${rhost}" "${remote_command}" 1>&3 2>&1 3>&- || echo "${rhost} connect error $?" |
-        awk -v pfx="${rhost}" '{printf "%30s :: ERROR %s\n", pfx, $0}'; } 3>&1 1>&2 |
-        awk -v pfx="${rhost}" '{printf "%30s ::       %s\n", pfx, $0}'
-    } &
+      ssh -A -T -q "${rhost}" "${remote_command}" \
+        2> >(awk -v pfx="${rhost}" -v dw="${dim_white}" -v dr="${dim_red}" -v rs="${reset}" \
+          '{printf "%s%30s%s %sXX %s%s\n", dw, pfx, rs, dr, $0, rs}' >&2) ||
+        echo "${rhost} connect error $?" |
+        awk -v pfx="${rhost}" -v dw="${dim_white}" -v dr="${dim_red}" -v rs="${reset}" \
+          '{printf "%s%30s%s %sXX %s%s\n", dw, pfx, rs, dr, $0, rs}' >&2
+    } |
+      awk -v pfx="${rhost}" -v dw="${dim_white}" -v g="${green}" -v rs="${reset}" \
+        '{printf "%s%30s%s %s::%s %s\n", dw, pfx, rs, g, rs, $0}' &
     pids+=($!)
   done
 
